'use Client'
import './css/mobile.css'
import './css/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'remixicon/fonts/remixicon.css'
import Script from 'next/script'
import Head from "next/head"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head> 
        <link rel="shortcut icon" href="./favicon.ico" />
      </Head>
      <Script async
          type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js" />
      <Script strategy='worker'  async
          type="text/javascript" src="/script/app.js" />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
